// <auto-generated />
namespace APITecsup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InvoiceandDetailv5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoiceandDetailv5));
        
        string IMigrationMetadata.Id
        {
            get { return "202111270117154_Invoice and Detail v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
