// <auto-generated />
namespace APITecsup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Createpersonv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createpersonv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202111270021296_Create person v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
